os:
  - linux
  # - osx
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  cpanm -n Devel::Cover::Report::Coveralls Test::Script
install:
  - cpanm --skip-satisfied --installdeps -q -n DBI::DBD DBI DBI::DBD::SqlEngine XML::Twig IPC::System::Simple autodie IPC::System::Simple Test::Pod::Spelling::CommonMistakes Test::Portability::Files
  - cpanm --skip-satisfied -q -n DBI::DBD DBI DBI::DBD::SqlEngine XML::Twig IPC::System::Simple autodie IPC::System::Simple Test::Pod::Spelling::CommonMistakes Test::Portability::Files
script:
  perl Makefile.PL && make && cover -test -report coveralls
