os:
  - linux
  # - osx
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  cpanm -n Devel::Cover::Report::Coveralls Test::Script
script:
  perl Makefile.PL && make && TRAVIS_TESTING=1 cover -test -report coveralls
